# Generated by Django 5.1 on 2024-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualvibes', '0002_keywordsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
        ),
    ]
