# Generated by Django 5.1 on 2024-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualvibes', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.CharField(max_length=10),
        ),
    ]
