# Generated by Django 5.1.1 on 2024-09-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualvibes', '0006_imagedata_rename_user_category_user_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageData',
            new_name='UserImageData',
        ),
    ]
