# Generated by Django 5.1 on 2024-09-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualvibes', '0008_photodata_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodata',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
