# Generated by Django 5.1 on 2024-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualvibes', '0011_remove_photodata_firstname_remove_photodata_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('likes', models.IntegerField()),
                ('bio', models.TextField()),
                ('images', models.ImageField(upload_to='visualvibes/upload')),
            ],
        ),
    ]
