# Generated by Django 5.1 on 2024-09-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualvibes', '0012_useruploadedimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruploadedimages',
            old_name='bio',
            new_name='description',
        ),
    ]
